
name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone hrani/moose-core PUBLIC repository
        uses: hrani/moose-core@main
        with:
          owner: 'hrani'
          repository: 'moose-core'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -l
          echo "CLONED REPO"
          cd poc-github-actions
          ls -l
