
name: nightly_e2e

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'hrani' }}
    env:
      PROJECT_NAME: "nightly_e2e"
    name: e2e tests
    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: moose-core
      uses: hrani/moose-core@v5

    
